name = "GAIA"
scheduler = "slurm"

install_path = "/mnt/lustre/gaia/yyacobovich/cloudai_install"
output_path = "/mnt/lustre/gaia/yyacobovich/workload_results"
default_partition = "GAIA"

gpus_per_node = 8
ntasks_per_node = 8

# extra_srun_args = "--reservation amaniz_85"

[[partitions]]
name = "GAIA"

[global_env_vars]
# NCCL Specific Configurations
NCCL_IB_HCA = "mlx5_0:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_9:1,mlx5_10:1,mlx5_11:1"

# UCX Specific Configurations
UCX_NET_DEVICES = "mlx5_0:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_9:1,mlx5_10:1,mlx5_11:1"

HF_HUB_OFFLINE = "1"
