name = "Israel-1"
scheduler = "slurm"
 
install_path = "./install"
output_path = "/auto/e2e/israel1/workload_results/yyacobovich"
default_partition = "ISR1-ALL"
 
gpus_per_node = 8
ntasks_per_node = 8
 
# cache_docker_images_locally = true
 
extra_srun_args = "--reservation sharonda_825"
 
[[partitions]]
name = "ISR1-ALL"
 
  [[partitions.groups]]
  name = "P2SU1"
  nodes = ["hgx-isr1-[001-016]"]
 
  [[partitions.groups]]
  name = "P2SU2"
  nodes = ["hgx-isr1-[017-032]"]
 
  [[partitions.groups]]
  name = "P1SU2"
  nodes = ["hgx-isr1-[033-064]"]
 
  [[partitions.groups]]
  name = "P1SU3"
  nodes = ["hgx-isr1-[065-096]"]
 
  [[partitions.groups]]
  name = "P1SU4"
  nodes = ["hgx-isr1-[097-128]"]
 
[[partitions]]
name = "ISR1-PRE"
 
[global_env_vars]
# NCCL General Configuration
NCCL_SOCKET_IFNAME = "eno8303"
 
# NCCL Specific Configurations
NCCL_COLLNET_ENABLE=1 
NCCL_ALGO="collnetdirect"
NCCL_IB_GID_INDEX = 3
NCCL_IB_TC = 96
NCCL_IB_HCA = "mlx5_0:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlYx5_6:1,mlx5_9:1,mlx5_10:1,mlx5_11:1"
NCCL_SHM_DISABLE=1
NCCL_P2P_DISABLE=1
NCCL_PXN_DISABLE=1
NCCL_IB_ADAPTIVE_ROUTING = "1"
NCCL_IB_SPLIT_DATA_ON_QPS = "0"
NCCL_IBEXT_DISABLE = "0"
NCCL_COLLNET_NODE_THRESHOLD=0
OMPI_MCA_btl = "tcp,self"
OMPI_MCA_btl_tcp_if_include = "eno8303"
 
# UCX Configuration
UCX_IB_GID_INDEX = "3"
UCX_IB_TRAFFIC_CLASS="96"
UCX_TLS = "rc,cuda_copy"
UCX_RNDV_SCHEME="put_zcopy"
 
# UCC Configuration
UCC_CLS = "basic"
UCC_TLS = "ucp"
UCC_COLL_TRACE = "info"
 
 
# Device Visibility Configuration
MELLANOX_VISIBLE_DEVICES = "0,3,4,5,6,9,10,11"
CUDA_VISIBLE_DEVICES = "0,1,2,3,4,5,6,7"
GLOO_SOCKET_IFNAME = "eno8303"
HYDRA_FULL_ERROR = "1"