# SPDX-FileCopyrightText: NVIDIA CORPORATION & AFFILIATES
# Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name = "l40s_bc_all_nccl_test"
[[Tests]]
id = "Tests.1"
template_test = "nccl_test_all_gather_worst"
num_nodes = "16"

[[Tests]]
id = "Tests.2"
template_test = "nccl_test_all_gather"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.1"
  time = 0


[[Tests]]
id = "Tests.3"
template_test = "nccl_test_all_reduce_worst"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.2"
  time = 0


[[Tests]]
id = "Tests.4"
template_test = "nccl_test_all_reduce"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.3"
  time = 0


[[Tests]]
id = "Tests.5"
template_test = "nccl_test_alltoall_worst_failover"
num_nodes = "16"
time_limit = "00:30:00"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.4"
  time = 0


[[Tests]]
id = "Tests.6"
template_test = "nccl_test_alltoall_worst"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.5"
  time = 0


[[Tests]]
id = "Tests.7"
template_test = "nccl_test_alltoall"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.6"
  time = 0


[[Tests]]
id = "Tests.8"
template_test = "nccl_test_bisection"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.7"
  time = 0


[[Tests]]
id = "Tests.9"
template_test = "nccl_test_broadcast"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.8"
  time = 0


[[Tests]]
id = "Tests.10"
template_test = "nccl_test_gather"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.9"
  time = 0


[[Tests]]
id = "Tests.11"
template_test = "nccl_test_hypercube"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.10"
  time = 0


[[Tests]]
id = "Tests.12"
template_test = "nccl_test_reduce_scatter_worst"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.11"
  time = 0


[[Tests]]
id = "Tests.13"
template_test = "nccl_test_reduce_scatter"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.12"
  time = 0


[[Tests]]
id = "Tests.14"
template_test = "nccl_test_reduce"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.13"
  time = 0


[[Tests]]
id = "Tests.15"
template_test = "nccl_test_scatter"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.14"
  time = 0


[[Tests]]
id = "Tests.16"
template_test = "nccl_test_sendrecv_worst"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.15"
  time = 0


[[Tests]]
id = "Tests.17"
template_test = "nccl_test_sendrecv"
num_nodes = "16"
  [[Tests.dependencies]]
  type = "end_post_comp"
  id = "Tests.16"
  time = 0
